# Generated by Django 5.1.4 on 2024-12-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_mailing', 'Может просматривать рассылки'), ('can_edit_mailing', 'Может редактировать рассылки'), ('can_delete_mailing', 'Может удалять рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
