# Generated by Django 5.1.4 on 2024-12-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('can_view_customer', 'Может просматривать получателей'), ('can_edit_customer', 'Может редактировать получателей'), ('can_delete_customer', 'Может удалять получателей')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('can_view_message', 'Может просматривать сообщение'), ('can_edit_message', 'Может редактировать сообщение'), ('can_delete_message', 'Может удалять сообщение')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
